### PR TITLE
fix: SecretStorage can now correctly store wildcard certs

### PR DESCRIPTION
**Pull request by gja**
This is a PR to #60. Also, this fixes one piece of the puzzle for #55.

### CODE REVIEW

**Comment by gja** [comment]
Also, as a side note, it would be great if this was pushed into it's own repository so that it's usable independently.

**Comment by gja** [comment]
hey, can someone help out over here? It's unable to pull a docker image @Embraser01

**Comment by Embraser01** [comment]
Hi @gja, thank you for openning this PR.

In which case the `.` char would be a problem?

**Comment by gja** [comment]
I'm using this as a standalone module (IE, I copied this file into my repo, though I'm not using the ingress controller).

The hostname in my caddy json looks like '*.foo.com'. When this becomes a secret, it becomes `prefix + ..foo.com`. This change will change that `prefix + .foo.com`

**Review by Embraser01 — APPROVED** [review]

**Comment by Embraser01** [comment]
Thanks!

**Pull request merged**
