### PR TITLE
bug fixes and helm setup updates

### PR DESCRIPTION
**Pull request by oreoluwa**

### CODE REVIEW

**Comment by mavimo** [comment]
@oreoluwa can you rebase this PR on master?

**Comment by hairyhenderson** [comment]
LGTM!

@mavimo I'll let you merge this if it looks good to you too.

**Comment by mavimo** [comment]
@hairyhenderson we have a PR that will re-build the chart, I'll try to integrate it once we merge https://github.com/caddyserver/ingress/pull/31

**Comment by mavimo** [comment]
@oreoluwa the pullSecret is already available in the new chart, about extra args we are moving them into configmap, so I think we can skip it for now, WDYT? If you agree feel free to close this PR, thx!

**Comment by oreoluwa** [comment]
Sounds fine @mavimo

**Pull request closed without merging**
