### PR TITLE
Release v1.0.0 of caddy-ingress-controller chart

### LINKED ISSUE #43: Can not install caddy-ingress-controller using helm install
I use helm installing the caddy-ingress-controller,but it failed with this error:
```
[root@boxing1 ~]#   helm install \
>     --namespace=caddy-system \
>     --repo https://caddyserver.github.io/ingress/ \
>     --atomic \
>     --set image.tag=latest \
>     mycaddy \
>     caddy-ingress-controller
Error: unknown flag: --atomic
```
My helm version is:
```
[root@boxing1 ~]# helm version --tls
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
I think this is because the too old helm version.Can we specify which helm version that we support?Thanks.

### LINKED ISSUE #71: helm can't find chart
Helm can not find the caddy-ingress-controller chart

    $ helm repo add caddyserver https://caddyserver.github.io/ingress/

    $ helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "caddyserver" chart repository
    Update Complete. ⎈ Happy Helming!⎈
    
    $ helm pull caddyserver/caddy-ingress-controller
    Error: chart "caddy-ingress-controller" matching  not found in caddyserver index. (try 'helm repo update'): no chart version found for caddy-ingress-controller-

    $ helm version
    version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

It shouldn't matter but this is in PowerShell on a Windows 10 Pro 64-bit machine.

### LINKED ISSUE #73: Error: chart "caddy-ingress-controller" not found in https://caddyserver.github.io/ingress/ repository
Hi,

I'm trying to deploy Caddy as an Ingress controller in my AKS cluster. When I try the provided commands, I get the following error:
`Error: chart "caddy-ingress-controller" not found in https://caddyserver.github.io/ingress/ repository`

I get the same error when adding the repo to my Helm repos first, and try to install the ingress controller then.

### LINKED ISSUE #77: Charts problem
Is there any problem with the official Charts warehouse? Please check it thoroughly.

### LINKED ISSUE #78: Warehouse problem
Error: chart "caddy-ingress-controller" not found in https://caddyserver.github.io/ingress repository

Is this problem during installation because the author deleted the repository?
企业微信截图_20211214101434

### LINKED ISSUE #79: Spinning startup
Hiya,

Using Caddy on K8's ( Client: 1.22.4  Server: 1.21.5 ).  When deploying to the cluster the caddy pod, spins every minute with these messages.  I can't for the life of me see where the resource name might be"  I have looked through the code and can't see any error lines with the caddy config reload: prefix.

Does anyone know what this error refers to? 

time="2022-01-03T13:58:55Z" level=info msg="Found TLS certificates on ingress resource. Syncing..."
time="2022-01-03T13:58:55Z" level=error msg="caddy config reload: resource name may not be empty"
time="2022-01-03T13:58:55Z" level=info msg="Ingress resource update detected, updating Caddy config..."
time="2022-01-03T13:58:55Z" level=info msg="Updating caddy config"
time="2022-01-03T13:58:55Z" level=info msg="using config map options: map[**redacted**]"

Thanks.

### PR DESCRIPTION
**Pull request by Embraser01**
Helm discard <1.0.0 versions so I bumped the chart version to 1.0.0 (not the app version).

Fixes #79 
Fixes #78 
Fixes #77 
Fixes #71
Fixes #73 
Fixes #43

### CODE REVIEW

**Comment by malthe** [comment]
@Embraser01 this does not address https://github.com/caddyserver/ingress/issues/79#issuecomment-1004161071 – no ingress rules are found because it is looking in the wrong place.

I think ...

**Comment by Embraser01** [comment]
@malthe I closed the issue because it was using an old version of the controller. We are now using only `networking.k8s.io/v1` apis

**Comment by malthe** [comment]
I'll have to see what is wrong on my end then because I still get:
```
time="2022-03-28T11:17:55Z" level=info msg="Found TLS certificates on ingress resource. Syncing..."
time="2022-03-28T11:17:55Z" level=error msg="caddy config reload: resource name may not be empty"
time="2022-03-28T11:17:56Z" level=info msg="Synching Ingress resource source addresses"
time="2022-03-28T11:17:56Z" level=info msg="skipping update of Ingress default/ingress-app (no change)"
time="2022-03-28T11:18:25Z" level=info msg="Ingress resource update detected, updating Caddy config..."
time="2022-03-28T11:18:25Z" level=info msg="Updating caddy config"
time="2022-03-28T11:18:25Z" level=info msg="using config map options: map[acmeCA: debug:false email:<email> metrics:true onDemandTLS:true proxyProtocol:false] to {Debug:false AcmeCA: Email:<email>}"
```
Infinitely looping; and I have one ingress resource in place.

**Comment by Embraser01** [comment]
I think you are on an old version of the controller (my guess would be before this PR #60)

**Comment by malthe** [comment]
@Embraser01 you're right – I needed to use `--set image.tag=v0.1.0` in order to force the system to use this image (probably had an older `latest` cached.)

Thanks!

**Comment by Embraser01** [comment]
Glad you fixed your issue!
It should be the default value on the last chart version
https://github.com/caddyserver/ingress/blob/9d0034236e5b1481d7cdec715dc3435ef1b4441f/charts/caddy-ingress-controller/values.yaml#L12

**Comment by malthe** [comment]
It is – but the frontpage of the repo (README) suggests putting `image.tag=latest` :-)

So I had that ... and ... yeah the rest is history. Anyway, thanks for your great work.

**Comment by Embraser01** [comment]
I see, will update it to remove this part or add a warning. Thanks!

**Pull request merged**
